//
//  Workspace.swift
//  klarna-iosManifests
//
//  Created by Jorge Palacio on 2024-10-09.
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "KlarnaSDKs",
    projects: [
        .relativeToCurrentFile("Libraries/\(KlarnaLibraries.core.rawValue)"),
        .relativeToCurrentFile("Libraries/\(KlarnaLibraries.nativeFunctions.rawValue)"),
        .relativeToCurrentFile("Libraries/\(KlarnaLibraries.webCore.rawValue)"),
        .relativeToCurrentFile("KlarnaSDKs/\(KlarnaSDKs.payments.rawValue)")
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
